default:
  image: amazoncorretto:17.0.8@sha256:4065444cc60404ae12deaa871cf96e40a598d8f02cec02910078f1d5f8a71a6e
  before_script:
    - ': before_script'
    - chmod +x mvnw
    - export MAVEN_OPTS="-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/"

# Static Application Security Testing (SAST) is a frequently used Application Security (AppSec) tool,
# which scans an applicationâ€™s source, binary, or byte code.
# https://www.microfocus.com/en-us/what-is/sast
include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  SAST_JAVA_VERSION: "17" # Required by SAST scanning
  OWASP_REPORT_NAME: "dependency-check-report.html"
  OWASP_REPORT_PATH: "target/$OWASP_REPORT_NAME"

cache:
  key: maven-cache
  paths:
    - $CI_PROJECT_DIR/.m2/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - ./mvnw verify $MAVEN_OPTS
    - echo 'Printing code coverage for Gitlab statistics'
    - cat coverage-report/target/site/jacoco-aggregate/index.html | grep -o '<tfoot>.*</tfoot>'
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - coverage-report/target/site/jacoco-aggregate
    expire_in: 1 hour

sonarcloud-check:
  needs:
    - job: test
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ./mvnw verify sonar:sonar -Dsonar.projectKey=ShowMeYourCodeYouTube_cqrs-and-event-sourcing-in-kotlin

build:
  stage: build
  script:
    # -U, --update-snapshots
    # Forces a check for updated releases and snapshots on remote repositories
    # Ref: https://books.sonatype.com/mvnref-book/reference/running-sect-options.html
    - ./mvnw clean install -U -DskipTests $MAVEN_OPTS

# !!! An alternative to SpotBugs / GitLab SAST !!!
# This is an example how to scan your project using publicly available plugins.
# The same can be achieved using other tools like build-in GitLab SAST (however the dashboard is not available for a standard/free account).
check-dependencies:
  stage: build
  allow_failure: true
  script:
    - ./mvnw package -DskipTests dependency-check:aggregate $MAVEN_OPTS
  artifacts:
    paths:
      - $OWASP_REPORT_PATH
    when: always
    expire_in: 1 hour
  only:
    - merge_requests
    - master

pages:
  stage: deploy
  variables:
    PUBLIC_COPY_FOLDER: "public-copy"
  script:
    - echo 'Cleaning old pages'
    # make a copy of all static pages
    - '[ -d public ] && echo "Found previous static resources" && cp -r public $PUBLIC_COPY_FOLDER'
    - rm -rf public
    - ls -la
    - mkdir -p public/test-report && cp -r coverage-report/target/site/jacoco-aggregate/* public/test-report
    - '[ -f "$OWASP_REPORT_PATH" ] && echo "Copying the latest OWASP report..." && cp $OWASP_REPORT_PATH public'
    - '[ ! -f "$OWASP_REPORT_PATH" ] && [ -d "$PUBLIC_COPY_FOLDER" ] && echo "Copying the previous OWASP report..." && cp $PUBLIC_COPY_FOLDER/$OWASP_REPORT_NAME public'
    - cp target/dependency-check-report.html public
    - echo 'Public directory content after copying files'
    - ls -la ./public
  artifacts:
    paths:
      - public
    expire_in: 1 hour
